# Generated by Django 2.2 on 2019-05-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='full_name',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='photo',
            new_name='picture',
        ),
    ]
